### ISSUE TITLE
fix examples in dat30

### ISSUE THREAD

**Issue by jangorecki** [ugcd/solarius#1]
There is an attempt to load `kinship2` namespace in examples [datasets.R#L47](https://github.com/ugcd/solarius/blob/49562c8b2732d3a96fe3e3a4f504e0dbcfb6eb81/R/datasets.R#L47), code below is the results from examples.
As `kinship2` is suggested dependency, it should not be required to run examples according to [R-exts](https://cran.r-project.org/doc/manuals/R-exts.html#Suggested-packages). This can be conditionally escaped with `requireNamespace`.
It is possible there are other cases of that issue in other examples, this one was to first that fails.

```
* checking examples ... ERROR
Running examples in ‘solarius-Ex.R’ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: dat30
> ### Title: dat30 data set adapted from multic R package
> ### Aliases: dat30 genocovdat30 mapdat30
> 
> ### ** Examples
> 
> data(dat30)
> 
> str(dat30)
'data.frame':   174 obs. of  10 variables:
 $ famid : int  1 1 1 1 1 1 2 2 2 2 ...
 $ id    : int  11 12 13 14 15 16 21 22 23 24 ...
 $ fa    : int  0 0 11 11 11 11 0 0 21 21 ...
 $ mo    : int  0 0 12 12 12 12 0 0 22 22 ...
 $ sex   : int  1 2 1 2 1 1 1 2 2 1 ...
 $ affect: int  2 2 2 2 2 2 2 2 2 2 ...
 $ class : logi  NA NA NA NA NA NA ...
 $ trait1: num  11.96 7.1 10.32 9.76 9.46 ...
 $ trait2: num  13.58 5.37 6.4 8.98 9.21 ...
 $ age   : int  50 25 35 49 51 45 37 29 39 41 ...
> 
> plotPed(dat30, 2) # plot the pedigree tree for family #2
Error: requireNamespace("kinship2", quietly = TRUE) is not TRUE
Execution halted
```

**Comment by variani** [comment]
I've fixed this by adding the kinship2 R package to the list of imported packages (See the DESCRIPTION file).

I'm not sure if this is an issue in other example files. Please let me know how I can reproduce your "check-examples" command, and I will try to fix other cases (if there are any).

I guess I missed this kinship2 issue, because I had the kinship2 package installed on my system.

Thanks for reporting!
