### ISSUE TITLE
issue running solarPolygenic - ibdprep failed

### ISSUE THREAD

**Issue by dpagliaccio** [ugcd/solarius#3]
Hello
I am trying to run the tutorial example: M1 <- solarPolygenic(trait1 ~ age + sex, data = dat30)

And I recieve the below error - do you know what might be causing this?
_Program ibdprep failed to run
Error in df2solar(df, dir, ...) : 
  file.exists(file.path(dir, "phi2.gz")) is not TRUE_

**Comment by variani** [comment]
Hi,

The output is not verbose, sorry about that. It says that the file "phi2.gz" was not generated, and this file represents the kinship matrix in SOLAR.

I would suggest to check your data frame `dat30`, for example, running the R package `kinship2`. Is `dat30` is the proper dataset `solarius`? Have you modified it in some way?

I haven't run solarius/SOLAR for a long time. It might happen that the new version of SOLAR processes data in a new way. What version of SOLAR do you use?

Best,
Andrey

**Comment by variani** [comment]
As a general suggestion, you can export your data to SOLAR file formats manually or using `df2solar` function. Then run SOLAR on terminal (not running solarius) and check if errors pop up.

I close this issue. Feel free to reopen it if you have further questions.
